// Application Logic
let network = null;
let currentNodes = new vis.DataSet();
let currentEdges = new vis.DataSet();
let allNodes = [];
let allEdges = [];

let focusedNodeId = null;
let shouldFollowFocus = false;
let draggedNodeId = null;
let isAnimating = false;

// Guided Nav
let diseaseNodes = [];
let currentDiseaseIndex = 0;

// Test Mode State
let isTestMode = false;
let testPool = [];
let currentTargetNode = null;
let hits = 0;
let misses = 0;

// DOM Elements
const loadingOverlay = document.getElementById('loading');
const networkContainer = document.getElementById('networkMap');
const searchInput = document.getElementById('searchInput');
const toggleBtns = document.querySelectorAll('.toggle-btn');
const infoPanel = document.getElementById('infoPanel');
const testPanel = document.getElementById('testPanel');
const guessInput = document.getElementById('guessInput');
const checkGuessBtn = document.getElementById('checkGuessBtn');
const nextTestBtn = document.getElementById('nextTestBtn');
const testFeedback = document.getElementById('testFeedback');
const hitsCount = document.getElementById('hitsCount');
const missesCount = document.getElementById('missesCount');
const studyModeBtn = document.getElementById('studyModeBtn');
const testModeBtn = document.getElementById('testModeBtn');

const infoTitle = document.getElementById('infoTitle');
const infoType = document.getElementById('infoType');
const infoConnections = document.getElementById('infoConnections');
const resetViewBtn = document.getElementById('resetViewBtn');

// Initialize visual network configuration
const options = {
  nodes: {
    font: {
      color: '#ffffff',
      face: 'Outfit',
      size: 14,
      strokeWidth: 2,
      strokeColor: '#000000'
    },
    borderWidth: 2,
    borderWidthSelected: 4,
    shadow: {
      enabled: true,
      color: 'rgba(0,0,0,0.5)',
      size: 10,
      x: 3,
      y: 3
    }
  },
  edges: {
    width: 1.5,
    color: {
      color: 'rgba(255,255,255,0.1)',
      highlight: '#3b82f6',
      hover: '#60a5fa'
    },
    smooth: {
      type: 'continuous'
    },
    selectionWidth: 2
  },
  groups: {
    disease: {
      color: {
        background: '#ef4444', 
        border: '#991b1b',
        highlight: { background: '#f87171', border: '#ef4444' },
        hover: { background: '#fca5a5', border: '#ef4444' }
      },
      font: { size: 18, bold: true },
      shape: 'dot'
    },
    symptom: {
      color: {
        background: '#10b981', 
        border: '#065f46',
        highlight: { background: '#34d399', border: '#10b981' },
        hover: { background: '#6ee7b7', border: '#10b981' }
      },
      font: { size: 14 },
      shape: 'box',
      shapeProperties: { borderRadius: 8 }
    }
  },
  physics: {
    enabled: true,
    barnesHut: {
      gravitationalConstant: -4000,
      centralGravity: 0.2,
      springLength: 150,
      springConstant: 0.04,
      damping: 0.40,
      avoidOverlap: 0.5
    },
    stabilization: {
      iterations: 200,
      fit: true
    },
    minVelocity: 0.75
  },
  interaction: {
    hover: true,
    tooltipDelay: 200,
    hideEdgesOnDrag: true,
    hideEdgesOnZoom: true
  }
};

// Start application
function initApp() {
  if (typeof mapData === 'undefined') {
    loadingOverlay.innerHTML = '<p>Erro: data.js não foi carregado.</p>';
    return;
  }

  allNodes = mapData.nodes;
  allEdges = mapData.edges;

  // Navigation Logic
  diseaseNodes = allNodes.filter(n => n.group === 'disease').sort((a,b) => a.id - b.id);

  currentNodes.add(allNodes);
  currentEdges.add(allEdges);
  
  // Ensure allEdges contains the IDs generated by vis.js
  allEdges = currentEdges.get();

  const data = {
    nodes: currentNodes,
    edges: currentEdges
  };

  network = new vis.Network(networkContainer, data, options);

  network.once("stabilizationIterationsDone", function () {
    loadingOverlay.style.opacity = '0';
    setTimeout(() => { loadingOverlay.style.display = 'none'; }, 500);

    // Auto-Focus on first disease
    if (diseaseNodes.length > 0) {
      focusOnDiseaseIndex(0);
    }
  });

  registerEvents();

  function trackNode() {
    if (shouldFollowFocus && focusedNodeId && draggedNodeId !== focusedNodeId && !isAnimating) {
      const pos = network.getPositions([focusedNodeId])[focusedNodeId];
      if (pos) {
        const viewPos = network.getViewPosition();
        const dx = pos.x - viewPos.x;
        const dy = pos.y - viewPos.y;
        
        if (Math.abs(dx) > 0.5 || Math.abs(dy) > 0.5) {
          const smoothFactor = 0.12; 
          network.moveTo({ 
            position: { x: viewPos.x + dx * smoothFactor, y: viewPos.y + dy * smoothFactor }, 
            animation: false 
          });
        }
      }
    }
    requestAnimationFrame(trackNode);
  }
  trackNode();
}

function registerEvents() {
  // Click event on the network
  network.on("click", function (params) {
    if (params.nodes.length > 0) {
      const nodeId = params.nodes[0];
      highlightNode(nodeId);
    } else {
      resetHighlights();
    }
  });

  network.on("dragStart", function (params) {
    if (params.nodes.length > 0) {
      draggedNodeId = params.nodes[0];
    } else {
      shouldFollowFocus = false;
    }
  });

  network.on("dragEnd", function (params) {
    draggedNodeId = null;
  });

  network.on("animationFinished", function() {
    isAnimating = false;
  });

  // Controls
  document.getElementById('zoomIn').addEventListener('click', () => {
    isAnimating = true;
    network.moveTo({ scale: network.getScale() * 1.5, animation: true });
  });
  
  document.getElementById('zoomOut').addEventListener('click', () => {
    isAnimating = true;
    network.moveTo({ scale: network.getScale() / 1.5, animation: true });
  });

  document.getElementById('fitView').addEventListener('click', () => {
    isAnimating = true;
    network.fit({ animation: true });
    resetHighlights();
  });

  // Guided Nav
  document.getElementById('prevDiseaseBtn').addEventListener('click', () => {
    focusOnDiseaseIndex(currentDiseaseIndex - 1);
  });

  document.getElementById('nextDiseaseBtn').addEventListener('click', () => {
    focusOnDiseaseIndex(currentDiseaseIndex + 1);
  });

  // Search filter
  searchInput.addEventListener('input', (e) => {
    const term = e.target.value.toLowerCase();
    
    if (term.length < 2) {
      currentNodes.update(allNodes.map(n => ({...n, hidden: false})));
      return;
    }

    const matchedNodes = allNodes.filter(n => n.label.toLowerCase().includes(term));
    const matchedIds = new Set(matchedNodes.map(n => n.id));
    
    // Highlight matched
    currentNodes.update(allNodes.map(n => {
      if (matchedIds.has(n.id)) {
        return { ...n, hidden: false, opacity: 1 };
      }
      return { ...n, hidden: false, opacity: 0.1 };
    }));
  });

  document.getElementById('resetViewBtn').addEventListener('click', () => {
    resetHighlights();
    network.fit({ animation: true });
  });

  toggleBtns.forEach(btn => {
    btn.addEventListener('click', (e) => {
      toggleBtns.forEach(b => b.classList.remove('active'));
      e.currentTarget.classList.add('active');
      filterNodes(e.currentTarget.dataset.filter);
    });
  });

  // Mode Switching
  studyModeBtn.addEventListener('click', () => switchMode('study'));
  testModeBtn.addEventListener('click', () => switchMode('test'));

  // Test Actions
  checkGuessBtn.addEventListener('click', handleGuess);
  guessInput.addEventListener('keypress', (e) => {
    if (e.key === 'Enter') handleGuess();
  });
  nextTestBtn.addEventListener('click', () => pickRandomDisease());
}

function switchMode(mode) {
  isTestMode = mode === 'test';
  
  if (isTestMode) {
    studyModeBtn.classList.remove('active');
    testModeBtn.classList.add('active');
    infoPanel.classList.add('hidden');
    testPanel.classList.remove('hidden');
    initTestMode();
  } else {
    studyModeBtn.classList.add('active');
    testModeBtn.classList.remove('active');
    testPanel.classList.add('hidden');
    resetHighlights();
  }
}

function initTestMode() {
  testPool = [...diseaseNodes];
  hits = 0;
  misses = 0;
  updateScoreUI();
  pickRandomDisease();
}

function pickRandomDisease() {
  if (testPool.length === 0) {
    alert("Parabéns! Você acertou todas as doenças. O jogo irá recomeçar.");
    initTestMode();
    return;
  }

  const randomIndex = Math.floor(Math.random() * testPool.length);
  currentTargetNode = testPool[randomIndex];
  
  // Reset UI
  guessInput.value = '';
  guessInput.disabled = false;
  checkGuessBtn.classList.remove('hidden');
  nextTestBtn.classList.add('hidden');
  testFeedback.classList.add('hidden');
  
  highlightNode(currentTargetNode.id);
}

function handleGuess() {
  const guess = guessInput.value.trim();
  if (!guess) return;

  // Sanitize actual name: remove text in parentheses and extra spaces
  const actualName = currentTargetNode.label;
  const sanitizedActual = actualName.replace(/\s*\(.*?\)\s*/g, ' ').trim();
  
  const matchPercent = calculateSimilarity(guess.toLowerCase(), sanitizedActual.toLowerCase());
  
  const isCorrect = matchPercent >= 0.8;

  if (isCorrect) {
    hits++;
    testPool = testPool.filter(n => n.id !== currentTargetNode.id);
    showTestFeedback(true, actualName);
  } else {
    misses++;
    showTestFeedback(false, actualName);
  }
  
  guessInput.disabled = true;
  checkGuessBtn.classList.add('hidden');
  nextTestBtn.classList.remove('hidden');
  updateScoreUI();
}

function showTestFeedback(isCorrect, actualName) {
  testFeedback.className = `test-feedback ${isCorrect ? 'success' : 'error'}`;
  testFeedback.innerHTML = isCorrect 
    ? `<i class="fa-solid fa-check-circle"></i> Correto! É <b>${actualName}</b>.` 
    : `<i class="fa-solid fa-times-circle"></i> Incorreto. Era <b>${actualName}</b>.`;
  testFeedback.classList.remove('hidden');
  
  // Reveal name on map temporarily by re-highlighting but with visibility
  // (In a real scenario, we'd just update the specific node in DataSet)
  highlightNode(currentTargetNode.id, true);
}

function updateScoreUI() {
  hitsCount.textContent = hits;
  missesCount.textContent = misses;
}

// Levenshtein Distance for typing tolerance
function calculateSimilarity(s1, s2) {
  let longer = s1;
  let shorter = s2;
  if (s1.length < s2.length) {
    longer = s2;
    shorter = s1;
  }
  const longerLength = longer.length;
  if (longerLength === 0) return 1.0;
  return (longerLength - editDistance(longer, shorter)) / parseFloat(longerLength);
}

function editDistance(s1, s2) {
  s1 = s1.toLowerCase();
  s2 = s2.toLowerCase();
  const costs = [];
  for (let i = 0; i <= s1.length; i++) {
    let lastValue = i;
    for (let j = 0; j <= s2.length; j++) {
      if (i === 0) costs[j] = j;
      else {
        if (j > 0) {
          let newValue = costs[j - 1];
          if (s1.charAt(i - 1) !== s2.charAt(j - 1))
            newValue = Math.min(Math.min(newValue, lastValue), costs[j]) + 1;
          costs[j - 1] = lastValue;
          lastValue = newValue;
        }
      }
    }
    if (i > 0) costs[s2.length] = lastValue;
  }
  return costs[s2.length];
}

function filterNodes(type) {
  resetHighlights();
  if (type === 'all') {
    currentNodes.update(allNodes.map(n => ({...n, hidden: false})));
    return;
  }
  
  const updates = allNodes.map(n => {
    if (n.group === type) {
      return { id: n.id, hidden: false, opacity: 1 };
    }
    return { id: n.id, hidden: false, opacity: 0.1 };
  });
  
  currentNodes.update(updates);
}

function highlightNode(nodeId, revealInTest = false) {
  focusedNodeId = nodeId;
  shouldFollowFocus = true;

  const selectedNode = currentNodes.get(nodeId);
  const connectedNodes = network.getConnectedNodes(nodeId);
  const connectedEdges = network.getConnectedEdges(nodeId);
  
  // Show in Sidebar
  if (isTestMode && !revealInTest) {
    // Specifically hide label in sidebar during test
  } else {
    showInfoPanel(selectedNode, connectedNodes);
  }
  
  // Dim everything else
  const nodeUpdates = allNodes.map(n => {
    let label = n.label;
    if (isTestMode && n.id === nodeId && !revealInTest) {
      label = "???";
    }

    if (n.id === nodeId) {
      return { id: n.id, label: label, hidden: false, opacity: 1, font: {bold: true} };
    } else if (connectedNodes.includes(n.id)) {
      return { id: n.id, hidden: false, opacity: 1 };
    } else {
      return { id: n.id, hidden: false, opacity: 0.05 };
    }
  });

  // Dim edges
  const edgeUpdates = allEdges.map(e => {
    if (connectedEdges.includes(e.id)) {
      return { id: e.id, hidden: false, opacity: 1, width: 2, color: { color: '#3b82f6'} };
    }
    return { id: e.id, hidden: false, opacity: 0.05, color: { color: 'rgba(255,255,255,0.05)'} };
  });

  currentNodes.update(nodeUpdates);
  currentEdges.update(edgeUpdates);
  
  // Focus on node
  isAnimating = true;
  network.focus(nodeId, {
    scale: 1.2,
    animation: { duration: 500, easingFunction: 'easeInOutQuad' }
  });
}

function resetHighlights() {
  focusedNodeId = null;
  shouldFollowFocus = false;
  
  infoPanel.classList.add('hidden');
  
  const nodeUpdates = allNodes.map(n => ({
    id: n.id,
    hidden: false,
    opacity: 1,
    font: {bold: n.group === 'disease'}
  }));
  
  const edgeUpdates = allEdges.map(e => ({
    id: e.id,
    hidden: false,
    opacity: 1,
    width: 1.5,
    color: { color: 'rgba(255,255,255,0.1)' }
  }));
  
  currentNodes.update(nodeUpdates);
  currentEdges.update(edgeUpdates);
}

function showInfoPanel(node, connectedIds) {
  if (isTestMode && node.id === currentTargetNode.id && testFeedback.classList.contains('hidden')) {
    infoTitle.textContent = "???";
  } else {
    infoTitle.textContent = node.label;
  }
  
  infoType.className = 'badge';
  if (node.group === 'disease') {
    infoType.textContent = 'Doença / Complicação';
    infoType.classList.add('disease');
  } else {
    infoType.textContent = 'Achado / Sinal Clínico';
    infoType.classList.add('symptom');
  }

  // Populate connections list
  infoConnections.innerHTML = '';
  
  const connectedNodes = connectedIds.map(id => currentNodes.get(id));
  
  // Sort alphabetically
  connectedNodes.sort((a,b) => a.label.localeCompare(b.label));

  connectedNodes.forEach(conn => {
    const li = document.createElement('li');
    li.textContent = conn.label;
    li.className = conn.group === 'disease' ? 'disease-conn' : 'symptom-conn';
    li.onclick = () => highlightNode(conn.id);
    infoConnections.appendChild(li);
  });

  infoPanel.classList.remove('hidden');
}

// Ensure DOM is loaded
window.addEventListener('DOMContentLoaded', initApp);

// Guided Nav Functions
function focusOnDiseaseIndex(index) {
  if (diseaseNodes.length === 0) return;
  
  if (index < 0) index = diseaseNodes.length - 1;
  if (index >= diseaseNodes.length) index = 0;
  
  currentDiseaseIndex = index;
  const node = diseaseNodes[currentDiseaseIndex];
  
  document.getElementById('navDiseaseName').textContent = node.label;
  document.getElementById('navCounter').textContent = `${currentDiseaseIndex + 1} / ${diseaseNodes.length}`;
  
  highlightNode(node.id);
}
