// Application Logic
let network = null;
let currentNodes = new vis.DataSet();
let currentEdges = new vis.DataSet();
let allNodes = [];
let allEdges = [];

let focusedNodeId = null;
let shouldFollowFocus = false;
let draggedNodeId = null;
let isAnimating = false;

// Guided Nav
let diseaseNodes = [];
let currentDiseaseIndex = 0;

// DOM Elements
const loadingOverlay = document.getElementById('loading');
const networkContainer = document.getElementById('networkMap');
const searchInput = document.getElementById('searchInput');
const toggleBtns = document.querySelectorAll('.toggle-btn');
const infoPanel = document.getElementById('infoPanel');
const infoTitle = document.getElementById('infoTitle');
const infoType = document.getElementById('infoType');
const infoConnections = document.getElementById('infoConnections');
const resetViewBtn = document.getElementById('resetViewBtn');

// Initialize visual network configuration
const options = {
  nodes: {
    font: {
      color: '#ffffff',
      face: 'Outfit',
      size: 14,
      strokeWidth: 2,
      strokeColor: '#000000'
    },
    borderWidth: 2,
    borderWidthSelected: 4,
    shadow: {
      enabled: true,
      color: 'rgba(0,0,0,0.5)',
      size: 10,
      x: 3,
      y: 3
    }
  },
  edges: {
    width: 1.5,
    color: {
      color: 'rgba(255,255,255,0.1)',
      highlight: '#3b82f6',
      hover: '#60a5fa'
    },
    smooth: {
      type: 'continuous'
    },
    selectionWidth: 2
  },
  groups: {
    disease: {
      color: {
        background: '#ef4444', 
        border: '#991b1b',
        highlight: { background: '#f87171', border: '#ef4444' },
        hover: { background: '#fca5a5', border: '#ef4444' }
      },
      font: { size: 18, bold: true },
      shape: 'dot'
    },
    symptom: {
      color: {
        background: '#10b981', 
        border: '#065f46',
        highlight: { background: '#34d399', border: '#10b981' },
        hover: { background: '#6ee7b7', border: '#10b981' }
      },
      font: { size: 14 },
      shape: 'box',
      shapeProperties: { borderRadius: 8 }
    }
  },
  physics: {
    enabled: true,
    barnesHut: {
      gravitationalConstant: -4000,
      centralGravity: 0.2,
      springLength: 150,
      springConstant: 0.04,
      damping: 0.15,
      avoidOverlap: 0.5
    },
    stabilization: {
      iterations: 200,
      fit: true
    },
    minVelocity: 0.75
  },
  interaction: {
    hover: true,
    tooltipDelay: 200,
    hideEdgesOnDrag: true,
    hideEdgesOnZoom: true
  }
};

// Start application
function initApp() {
  if (typeof mapData === 'undefined') {
    loadingOverlay.innerHTML = '<p>Erro: data.js não foi carregado.</p>';
    return;
  }

  allNodes = mapData.nodes;
  allEdges = mapData.edges;

  // Navigation Logic
  diseaseNodes = allNodes.filter(n => n.group === 'disease').sort((a,b) => a.id - b.id);

  currentNodes.add(allNodes);
  currentEdges.add(allEdges);
  
  // Ensure allEdges contains the IDs generated by vis.js
  allEdges = currentEdges.get();

  const data = {
    nodes: currentNodes,
    edges: currentEdges
  };

  network = new vis.Network(networkContainer, data, options);

  network.once("stabilizationIterationsDone", function () {
    loadingOverlay.style.opacity = '0';
    setTimeout(() => { loadingOverlay.style.display = 'none'; }, 500);

    // Auto-Focus on first disease
    if (diseaseNodes.length > 0) {
      focusOnDiseaseIndex(0);
    }
  });

  registerEvents();

  function trackNode() {
    if (shouldFollowFocus && focusedNodeId && draggedNodeId !== focusedNodeId && !isAnimating) {
      const pos = network.getPositions([focusedNodeId])[focusedNodeId];
      if (pos) {
        const viewPos = network.getViewPosition();
        const dx = pos.x - viewPos.x;
        const dy = pos.y - viewPos.y;
        
        if (Math.abs(dx) > 0.5 || Math.abs(dy) > 0.5) {
          const smoothFactor = 0.12; 
          network.moveTo({ 
            position: { x: viewPos.x + dx * smoothFactor, y: viewPos.y + dy * smoothFactor }, 
            animation: false 
          });
        }
      }
    }
    requestAnimationFrame(trackNode);
  }
  trackNode();
}

function registerEvents() {
  // Click event on the network
  network.on("click", function (params) {
    if (params.nodes.length > 0) {
      const nodeId = params.nodes[0];
      highlightNode(nodeId);
    } else {
      resetHighlights();
    }
  });

  network.on("dragStart", function (params) {
    if (params.nodes.length > 0) {
      draggedNodeId = params.nodes[0];
    } else {
      shouldFollowFocus = false;
    }
  });

  network.on("dragEnd", function (params) {
    draggedNodeId = null;
  });

  network.on("animationFinished", function() {
    isAnimating = false;
  });

  // Controls
  document.getElementById('zoomIn').addEventListener('click', () => {
    isAnimating = true;
    network.moveTo({ scale: network.getScale() * 1.5, animation: true });
  });
  
  document.getElementById('zoomOut').addEventListener('click', () => {
    isAnimating = true;
    network.moveTo({ scale: network.getScale() / 1.5, animation: true });
  });

  document.getElementById('fitView').addEventListener('click', () => {
    isAnimating = true;
    network.fit({ animation: true });
    resetHighlights();
  });

  // Guided Nav
  document.getElementById('prevDiseaseBtn').addEventListener('click', () => {
    focusOnDiseaseIndex(currentDiseaseIndex - 1);
  });

  document.getElementById('nextDiseaseBtn').addEventListener('click', () => {
    focusOnDiseaseIndex(currentDiseaseIndex + 1);
  });

  // Search filter
  searchInput.addEventListener('input', (e) => {
    const term = e.target.value.toLowerCase();
    
    if (term.length < 2) {
      currentNodes.update(allNodes.map(n => ({...n, hidden: false})));
      return;
    }

    const matchedNodes = allNodes.filter(n => n.label.toLowerCase().includes(term));
    const matchedIds = new Set(matchedNodes.map(n => n.id));
    
    // Highlight matched
    currentNodes.update(allNodes.map(n => {
      if (matchedIds.has(n.id)) {
        return { ...n, hidden: false, opacity: 1 };
      }
      return { ...n, hidden: false, opacity: 0.1 };
    }));
  });

  document.getElementById('resetViewBtn').addEventListener('click', () => {
    resetHighlights();
    network.fit({ animation: true });
  });

  toggleBtns.forEach(btn => {
    btn.addEventListener('click', (e) => {
      toggleBtns.forEach(b => b.classList.remove('active'));
      e.currentTarget.classList.add('active');
      filterNodes(e.currentTarget.dataset.filter);
    });
  });
}

function filterNodes(type) {
  resetHighlights();
  if (type === 'all') {
    currentNodes.update(allNodes.map(n => ({...n, hidden: false})));
    return;
  }
  
  const updates = allNodes.map(n => {
    if (n.group === type) {
      return { id: n.id, hidden: false, opacity: 1 };
    }
    return { id: n.id, hidden: false, opacity: 0.1 };
  });
  
  currentNodes.update(updates);
}

function highlightNode(nodeId) {
  focusedNodeId = nodeId;
  shouldFollowFocus = true;

  const selectedNode = currentNodes.get(nodeId);
  const connectedNodes = network.getConnectedNodes(nodeId);
  const connectedEdges = network.getConnectedEdges(nodeId);
  
  // Show in Sidebar
  showInfoPanel(selectedNode, connectedNodes);
  
  // Dim everything else
  const nodeUpdates = allNodes.map(n => {
    if (n.id === nodeId) {
      return { id: n.id, hidden: false, opacity: 1, font: {bold: true} };
    } else if (connectedNodes.includes(n.id)) {
      return { id: n.id, hidden: false, opacity: 1 };
    } else {
      return { id: n.id, hidden: false, opacity: 0.05 };
    }
  });

  // Dim edges
  const edgeUpdates = allEdges.map(e => {
    if (connectedEdges.includes(e.id)) {
      return { id: e.id, hidden: false, opacity: 1, width: 2, color: { color: '#3b82f6'} };
    }
    return { id: e.id, hidden: false, opacity: 0.05, color: { color: 'rgba(255,255,255,0.05)'} };
  });

  currentNodes.update(nodeUpdates);
  currentEdges.update(edgeUpdates);
  
  // Focus on node
  isAnimating = true;
  network.focus(nodeId, {
    scale: 1.2,
    animation: { duration: 500, easingFunction: 'easeInOutQuad' }
  });
}

function resetHighlights() {
  focusedNodeId = null;
  shouldFollowFocus = false;
  
  infoPanel.classList.add('hidden');
  
  const nodeUpdates = allNodes.map(n => ({
    id: n.id,
    hidden: false,
    opacity: 1,
    font: {bold: n.group === 'disease'}
  }));
  
  const edgeUpdates = allEdges.map(e => ({
    id: e.id,
    hidden: false,
    opacity: 1,
    width: 1.5,
    color: { color: 'rgba(255,255,255,0.1)' }
  }));
  
  currentNodes.update(nodeUpdates);
  currentEdges.update(edgeUpdates);
}

function showInfoPanel(node, connectedIds) {
  infoTitle.textContent = node.label;
  
  infoType.className = 'badge';
  if (node.group === 'disease') {
    infoType.textContent = 'Doença / Complicação';
    infoType.classList.add('disease');
  } else {
    infoType.textContent = 'Achado / Sinal Clínico';
    infoType.classList.add('symptom');
  }

  // Populate connections list
  infoConnections.innerHTML = '';
  
  const connectedNodes = connectedIds.map(id => currentNodes.get(id));
  
  // Sort alphabetically
  connectedNodes.sort((a,b) => a.label.localeCompare(b.label));

  connectedNodes.forEach(conn => {
    const li = document.createElement('li');
    li.textContent = conn.label;
    li.className = conn.group === 'disease' ? 'disease-conn' : 'symptom-conn';
    li.onclick = () => highlightNode(conn.id);
    infoConnections.appendChild(li);
  });

  infoPanel.classList.remove('hidden');
}

// Ensure DOM is loaded
window.addEventListener('DOMContentLoaded', initApp);

// Guided Nav Functions
function focusOnDiseaseIndex(index) {
  if (diseaseNodes.length === 0) return;
  
  if (index < 0) index = diseaseNodes.length - 1;
  if (index >= diseaseNodes.length) index = 0;
  
  currentDiseaseIndex = index;
  const node = diseaseNodes[currentDiseaseIndex];
  
  document.getElementById('navDiseaseName').textContent = node.label;
  document.getElementById('navCounter').textContent = `${currentDiseaseIndex + 1} / ${diseaseNodes.length}`;
  
  highlightNode(node.id);
}
